Fix path for unreleased demo packages

diff --git a/ros2_debian/Dockerfile.debian12 b/ros2_debian/Dockerfile.debian12
--- a/ros2_debian/Dockerfile.debian12
+++ b/ros2_debian/Dockerfile.debian12
@@ -165,7 +165,7 @@ RUN \
   mkdir -p src/imported_pkgs && \
   vcs import src/imported_pkgs < "$repo_file" && \
   TARGET_PACKAGES=$(colcon list --base-paths src/imported_pkgs --names-only | tr '\n' ' ') && \
-  UNRELEASED_PACKAGES=$(rosdep keys --from-path src/imported_pkgs/ros2_control_demos/ | tr '\n' ' ') && \
+  UNRELEASED_PACKAGES=$(rosdep keys --from-path src/imported_pkgs/ros-controls/ros2_control_demos/ | tr '\n' ' ') && \
   if [ -z "$TARGET_PACKAGES" ]; then \
     echo "No packages found in imported repos" >&2; \
     exit 1; \
@@ -185,18 +185,21 @@ RUN \
     exit 1; \
   fi && \
 
-  success=0 && \
-  for i in 1 2 3 4 5; do \
-    if rosinstall_generator $UNRELEASED_PACKAGES --rosdistro $ROS_DISTRO --deps --format repos --exclude $EXCLUDE_PACKAGES $TARGET_PACKAGES  > deps_unreleased.repos; then \
-      success=1; \
-      break; \
-    fi; \
-    echo "retry #${i} .."; \
-    sleep 60; \
-  done && \
-  if [ "$success" -ne 1 ] || [ ! -s deps_unreleased.repos ]; then \
-    echo "Failed to generate deps_unreleased.repos" >&2; \
-    exit 1; \
+
+  if [ -n "$UNRELEASED_PACKAGES" ]; then \
+    success=0 && \
+    for i in 1 2 3 4 5; do \
+      if rosinstall_generator $UNRELEASED_PACKAGES --rosdistro $ROS_DISTRO --deps --format repos --exclude $EXCLUDE_PACKAGES $TARGET_PACKAGES  > deps_unreleased.repos; then \
+        success=1; \
+        break; \
+      fi; \
+      echo "retry #${i} .."; \
+      sleep 60; \
+    done && \
+    if [ "$success" -ne 1 ] || [ ! -s deps_unreleased.repos ]; then \
+      echo "Failed to generate deps_unreleased.repos" >&2; \
+      exit 1; \
+    fi && \
   fi && \
 
   # import repos and install dependencies via rosdep
